from ..config import GLOBAL_LAYERS

GLOBAL_LAYERS["WAFER_OUTLINE"] = (52, 1)

GLOBAL_LAYERS["MASK_OUTLINE"] = (61, 2)

GLOBAL_LAYERS["ALIGNMENT_MARKS"] = (11, 0)
GLOBAL_LAYERS["CONTACT_DOPING"] = (12, 0)
GLOBAL_LAYERS["METALIZATION"] = (13, 0)
